### ISSUE TITLE
 parse error unexpected ',' for comma separated rules like font or box-shadow 

### ISSUE THREAD

**Issue by jlangston** [tomyeh/ZUSS#11]
with a rule like 

``` css
p {
  font: 12px Arial, Helvetica, sans-serif;
  box-shadow:  2px 1px 2px 1px #bababa, 2px -1px 2px 1px #bababa
}

```

 I get  a parse exception 

``` java
Exception in thread "main" org.zkoss.zuss.ZussException: [zuss] test.zuss:Line 76: unexpected ','
        at org.zkoss.zuss.impl.in.Parser.error(Parser.java:72)
        at org.zkoss.zuss.impl.in.Parser.parseStyle(Parser.java:325)
        at org.zkoss.zuss.impl.in.Parser.parse(Parser.java:112)
        at org.zkoss.zuss.impl.in.Parser.newBlock(Parser.java:169)
        at org.zkoss.zuss.impl.in.Parser.parseSelector(Parser.java:306)
        at org.zkoss.zuss.impl.in.Parser.parse(Parser.java:105)
        at org.zkoss.zuss.impl.in.Parser.parse(Parser.java:87)
        at org.zkoss.zuss.Zuss.parse(Zuss.java:69)
        at org.zkoss.zuss.Zuss.parse(Zuss.java:56)
        at org.zkoss.zuss.Zuss.parse(Zuss.java:41)
        at org.zkoss.zuss.Zuss.main(Zuss.java:151)
```

line 76 in this particular file happens to be a font rule like above.

**Comment by jlangston** [comment]
I realized I was using an old version. This isn't a valid issue on the latest release
